<a href="https://colab.research.google.com/github/kirtichandrachoudhury/Lab-Assignment/blob/main/Dataset_importing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
url = 'https://raw.githubusercontent.com/GouriNayak/DMDW/main/Data.csv'

In [2]:
import pandas as pd

In [3]:
data =pd.read_csv(url)

In [4]:

data

age gender   income  spending
0   22       m   18000      6000
1   25       f   30000      8000
2   31       f   35000     12000
3   35       m   40000     18000

In [5]:
from google.colab import files

In [ ]:
uploaded = files.upload()

In [7]:
data

age gender   income  spending
0   22       m   18000      6000
1   25       f   30000      8000
2   31       f   35000     12000
3   35       m   40000     18000

In [8]:
import io

In [10]:
df1 = pd.read_csv(io.BytesIO(uploaded['Data.csv']))

In [11]:
import numpy

In [12]:
arr=numpy.array([1,2,3,4,5])

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:

import numpy as np

In [15]:
arr=np.array([1,2,3,4,5])

In [16]:
print(arr)

[1 2 3 4 5]


In [17]:
import numpy as np

In [18]:
print('np._version_')

np._version_


In [19]:
import numpy as np

In [20]:
arr=np.array([1,2,3,4,5])

In [21]:
print(arr)

[1 2 3 4 5]


In [22]:
print(type(arr))

<class 'numpy.ndarray'>
